In [43]:
import pandas as pd
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [44]:
### load the trained model, scaler pickel and onehot
model = load_model("model.h5")

## load the encoder and scalar
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    label_encoder_geo = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [45]:
### Example input data for prediction
input_data = {
    'CreditScore': 600,
    'Geography':'France',
    'Gender': 'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [46]:
## convert the values into numerical
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns= label_encoder_geo.get_feature_names_out(['Geography']))

c:\kaizen\deeplearning\ANN\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [47]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [48]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [49]:
### Encode Categorical Variables
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [50]:
### Combine one-hot encoded columns with input data
input_df = pd.concat([input_df.drop(['Geography'], axis=1), geo_encoded_df], axis=1)

In [53]:
### Scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [55]:
### Prediction
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 28ms/step

array([[0.01544038]], dtype=float32)

In [57]:
prediction_proba = prediction[0][0]
prediction_proba

0.015440383

In [58]:
if prediction_proba>0.5:
    print('Customer is likely to churn')
else:
    print('Customer is not likely to churn')

Customer is not likely to churn